# Docker Compose per ambiente di sviluppo
# Utilizza il server di sviluppo di Astro con hot reload
version: '3.8'

services:
  blog-dev:
    # Immagine Node.js per sviluppo
    image: node:20-alpine
    
    # Directory di lavoro nel container
    working_dir: /app
    
    # Monta il codice sorgente per hot reload
    volumes:
      - .:/app
      - /app/node_modules  # Evita conflitti con node_modules locali
    
    # Porta del server di sviluppo Astro (default: 4321)
    ports:
      - "1234:80"
    
    # Variabili d'ambiente per sviluppo
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0  # Permette accesso esterno al container
    
    # Comando per avviare il server di sviluppo
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    
    # Mantiene il container attivo
    stdin_open: true
    tty: true
    
    # Riavvia automaticamente in caso di crash
    restart: unless-stopped
